import json
import os
from datetime import datetime
from .screener import ScreeningResult
from .pool_inference import AIPoolRanking


class PoolReporter:
    def print(self, result: ScreeningResult, top_n: int = 5):
        ai = result.aiResult
        rankings = ai.rankings[:top_n]

        print("\n")
        print("📈 GROQ STRATEGIC PORTFOLIO ANALYSIS")
        print(f"   Analyzed: {result.totalAnalyzed} pools  |  {datetime.now().isoformat()}\n")
        print("   ✅ Rankings generated by 0G Compute Sealed AI (TEE-verified, comparative)\n")

        print("📈 AI Market Summary:")
        print(f"   {ai.summary}\n")

        header = (
            self._pad("Rank", 6) + self._pad("Pool", 14) + self._pad("Decision", 10) +
            self._pad("Risk", 7) + self._pad("Confidence", 12) +
            self._pad("Est. Return", 13) + "AI Reasoning (brief)"
        )
        print(header)
        print("─" * 100)
        for entry in rankings:
            print(self._format_row(entry))
        print("─" * 100)

        top = ai.bestPool
        print(f"\n🏆  BEST POOL TO INVEST: {top.poolName}")
        print(f"    Decision       : {top.action.upper()}")
        print(f"    Risk Score      : {top.riskScore}/10")
        print(f"    AI Confidence   : {top.confidenceScore}/100")
        print(f"    Expected Return : {top.expectedReturn}")
        print(f"\n    🧠 Full AI Reasoning:")
        print(f'    "{top.reasoning}"')

        if top.analysis_breakdown:
            ab = top.analysis_breakdown
            print(f"\n    🎯 STRATEGIC DEEP-DIVE (QUADRANT ANALYSIS):")
            print(f"     • 🌐 Sentiment : {ab.get('market_sentiment', '')}")
            print(f"     • 🧬 Technical : {ab.get('technical_health', '')}")
            print(f"     • 💰 Yield     : {ab.get('yield_analysis', '')}")
            print(f"     • 🛡️  Risk      : {ab.get('risk_mitigation', '')}")

        print("\n    🔐 Source: 0G Compute Sealed Inference — privacy-preserved, TEE-verified.")
        print("\n" + "═" * 100 + "\n")

    def export_json(self, result: ScreeningResult, output_dir: str = ".") -> str:
        filename = f"pool-report-{result.timestamp}.json"
        out_path = os.path.join(os.path.abspath(output_dir), filename)
        import dataclasses
        export_data = {
            "generatedAt": datetime.fromtimestamp(result.timestamp / 1000).isoformat(),
            "aiEngine": "LOCAL_FALLBACK" if result.aiResult.usedFallback else "0G_COMPUTE_TEE",
            "totalAnalyzed": result.totalAnalyzed,
            "topPick": result.aiResult.bestPool.poolName,
            "marketSummary": result.aiResult.summary,
            "rankings": [dataclasses.asdict(r) for r in result.aiResult.rankings],
            "inputPools": [dataclasses.asdict(p) for p in result.inputPools],
        }
        with open(out_path, "w") as f:
            json.dump(export_data, f, indent=2)
        print(f"\n💾 [Report] Full AI analysis exported → {out_path}")
        return out_path

    def _format_row(self, r: AIPoolRanking) -> str:
        rank_label = {1: "🥇 #1", 2: "🥈 #2", 3: "🥉 #3"}.get(r.rank, f"    #{r.rank}")
        action_str = r.action.upper()
        short_reason = r.reasoning[:45] + "…" if len(r.reasoning) > 45 else r.reasoning
        return (
            self._pad(rank_label, 6) + self._pad(r.poolName, 14) +
            self._pad(action_str, 10) + self._pad(f"{r.riskScore}/10", 7) +
            self._pad(f"{r.confidenceScore}/100", 12) +
            self._pad(r.expectedReturn, 13) + short_reason
        )

    def _pad(self, s: str, length: int) -> str:
        return s + " " * max(0, length - len(s))
